// Jibbitz Trends - Data Layer
// In production, feed from social listening APIs (Brandwatch, Sprout Social, Google Trends)

const JIBBITZ_TRENDS = [
  {
    id: "punch-monkey",
    name: "Punch the Monkey",
    category: "animals",
    description: "Baby spider monkey at Zoo Atlanta who went viral for clutching his stuffed animal. 200M+ views across platforms. Pure joy content.",
    source: "TikTok / Instagram",
    daysTrending: 12,
    socialVolume: 4200000,
    velocity: 98, // 0-100 how fast it's accelerating
    sentiment: 97,
    jibbitzScore: 99,
    stage: "launched",
    stageDetail: "Launched Mar 1 — best-performing social post ever, massive PR pickup",
    searchTrend: [5, 8, 15, 40, 78, 95, 100, 92, 88, 85, 80, 76, 70, 65],
  },
  {
    id: "moo-deng-2",
    name: "Moo Deng Baby",
    category: "animals",
    description: "The pygmy hippo is back — Moo Deng's baby was born at Khao Kheow Zoo. Internet is losing it again. Even cuter than the original.",
    source: "TikTok / X / Instagram",
    daysTrending: 5,
    socialVolume: 8900000,
    velocity: 96,
    sentiment: 99,
    jibbitzScore: 97,
    stage: "design",
    stageDetail: "Design in progress — rush production recommended",
    searchTrend: [0, 0, 2, 5, 20, 55, 88, 96, 100, 98, 95, 92, 90, 88],
  },
  {
    id: "capybara-hot-spring",
    name: "Onsen Capybara",
    category: "animals",
    description: "Capybara soaking in Japanese hot springs with a yuzu orange on its head. Resurging every winter but 2026 version with the tiny towel broke records.",
    source: "X / Reddit / TikTok",
    daysTrending: 18,
    socialVolume: 3100000,
    velocity: 62,
    sentiment: 96,
    jibbitzScore: 91,
    stage: "evaluation",
    stageDetail: "High potential — evaluate seasonal limited edition",
    searchTrend: [10, 12, 15, 20, 35, 55, 72, 80, 85, 82, 78, 72, 65, 60],
  },
  {
    id: "dubai-chocolate",
    name: "Dubai Chocolate Bar",
    category: "food",
    description: "Fix Dessert Chocolatier's pistachio kunafa chocolate bar. Everyone is making dupes. The green cross-section is iconic and instantly recognizable.",
    source: "TikTok / Instagram / YouTube",
    daysTrending: 45,
    socialVolume: 12000000,
    velocity: 45,
    sentiment: 88,
    jibbitzScore: 85,
    stage: "evaluation",
    stageDetail: "Strong visual identity — the green/brown cross section is very Jibbitz-friendly",
    searchTrend: [30, 35, 50, 70, 85, 95, 100, 98, 92, 85, 78, 70, 62, 55],
  },
  {
    id: "pedro-raccoon",
    name: "Pedro Pedro Pedro",
    category: "memes",
    description: "Dancing raccoon meme set to Raffaella Carrà song. Absurdist humor, endlessly remixed. The raccoon silhouette is a perfect charm shape.",
    source: "TikTok / Instagram Reels",
    daysTrending: 30,
    socialVolume: 6500000,
    velocity: 55,
    sentiment: 94,
    jibbitzScore: 88,
    stage: "evaluation",
    stageDetail: "Meme longevity confirmed — 30+ days and still growing",
    searchTrend: [5, 10, 25, 45, 60, 75, 82, 88, 92, 90, 88, 85, 82, 80],
  },
  {
    id: "pickle-everything",
    name: "Pickle Mania",
    category: "food",
    description: "Pickles are having a cultural moment — pickle Dr Pepper, pickle candy, pickle ornaments. Gen Z is obsessed. Simple, funny, iconic shape.",
    source: "TikTok / Retail / X",
    daysTrending: 60,
    socialVolume: 5200000,
    velocity: 40,
    sentiment: 82,
    jibbitzScore: 90,
    stage: "production",
    stageDetail: "In production — pickle Jibbitz set (3-pack: whole, slice, jar)",
    searchTrend: [20, 25, 30, 38, 45, 55, 62, 68, 72, 75, 78, 80, 82, 80],
  },
  {
    id: "caitlin-clark",
    name: "Caitlin Clark Fever",
    category: "sports",
    description: "WNBA viewership records shattered. Clark is the most-searched athlete in the US. Her signature celebration (the goggles) is iconic.",
    source: "ESPN / X / TikTok",
    daysTrending: 90,
    socialVolume: 15000000,
    velocity: 70,
    sentiment: 85,
    jibbitzScore: 82,
    stage: "evaluation",
    stageDetail: "Licensing required — explore partnership opportunity",
    searchTrend: [40, 42, 48, 55, 60, 65, 72, 78, 82, 88, 90, 92, 95, 92],
  },
  {
    id: "bluey-season4",
    name: "Bluey Season 4",
    category: "characters",
    description: "New Bluey season dropped — parents and kids equally obsessed. Bluey, Bingo, and Muffin are the top 3 requested character Jibbitz on socials.",
    source: "Disney+ / TikTok / X",
    daysTrending: 14,
    socialVolume: 9500000,
    velocity: 88,
    sentiment: 98,
    jibbitzScore: 94,
    stage: "production",
    stageDetail: "Licensed — Bluey S4 character pack in production, targeting Apr release",
    searchTrend: [15, 18, 25, 35, 50, 70, 85, 92, 98, 100, 95, 90, 88, 85],
  },
  {
    id: "cottage-cheese",
    name: "Cottage Cheese Era",
    category: "food",
    description: "Cottage cheese recipes dominating food TikTok. The lumpy texture is oddly perfect for a 3D Jibbitz. Ties into health/wellness positioning.",
    source: "TikTok / Instagram",
    daysTrending: 40,
    socialVolume: 2800000,
    velocity: 35,
    sentiment: 78,
    jibbitzScore: 65,
    stage: "watching",
    stageDetail: "Niche but sticky — monitor for crossover into mainstream meme territory",
    searchTrend: [15, 18, 22, 28, 35, 40, 45, 48, 50, 52, 54, 55, 56, 55],
  },
  {
    id: "grimace-shake",
    name: "Grimace Renaissance",
    category: "characters",
    description: "McDonald's brought Grimace back permanently. The purple blob is everywhere again. Already a beloved Jibbitz shape from 2023 — restock opportunity.",
    source: "X / TikTok / Retail",
    daysTrending: 20,
    socialVolume: 3800000,
    velocity: 58,
    sentiment: 91,
    jibbitzScore: 78,
    stage: "evaluation",
    stageDetail: "Licensing check — previous collab expired, renegotiate for restock",
    searchTrend: [8, 10, 15, 22, 35, 50, 65, 72, 78, 80, 78, 75, 70, 68],
  },
  {
    id: "panda-twins",
    name: "National Zoo Panda Twins",
    category: "animals",
    description: "Bao Li and Qing Bao's twin cubs debuted at the National Zoo. Panda-mania is back. DC tourists are buying anything panda-shaped.",
    source: "News / Instagram / TikTok",
    daysTrending: 8,
    socialVolume: 5600000,
    velocity: 85,
    sentiment: 99,
    jibbitzScore: 92,
    stage: "design",
    stageDetail: "Fast-track design — twin panda set, bamboo accessory",
    searchTrend: [0, 0, 5, 15, 40, 65, 82, 90, 95, 98, 100, 97, 94, 90],
  },
  {
    id: "stanley-cup",
    name: "Stanley x Crocs Crossover",
    category: "pop-culture",
    description: "People are matching their Stanley cup colors to their Crocs. User-generated trend — the color-coordination content is organic and growing.",
    source: "TikTok / Instagram",
    daysTrending: 22,
    socialVolume: 1800000,
    velocity: 50,
    sentiment: 90,
    jibbitzScore: 86,
    stage: "evaluation",
    stageDetail: "Explore Stanley collab — mini Stanley cup Jibbitz would break the internet",
    searchTrend: [5, 8, 12, 18, 25, 35, 42, 48, 55, 60, 62, 65, 68, 70],
  },
];

const JIBBITZ_PIPELINE = [
  { stage: "watching", label: "Watching", icon: "👁️", color: "#6b7280" },
  { stage: "evaluation", label: "Evaluating", icon: "🔍", color: "#f59e0b" },
  { stage: "design", label: "In Design", icon: "🎨", color: "#3b82f6" },
  { stage: "production", label: "In Production", icon: "🏭", color: "#8b5cf6" },
  { stage: "launched", label: "Launched", icon: "🚀", color: "#43B02A" },
];

const JIBBITZ_WINS = [
  {
    name: "Punch the Monkey",
    launchDate: "2026-03-01",
    socialLikes: "2.4M",
    prPickups: 47,
    salesImpact: "Best-selling single Jibbitz in Q1 2026",
    highlight: "Most-liked Crocs social post of all time",
    lessonsLearned: "Speed was everything — 8 days from trend detection to launch. The emotional connection (baby animal + stuffed toy) drove sharing.",
  },
  {
    name: "Moo Deng (Original)",
    launchDate: "2024-10-15",
    socialLikes: "1.8M",
    prPickups: 32,
    salesImpact: "Sold out in 4 hours, 3 restocks",
    highlight: "Drove 340% spike in Crocs.com traffic from non-US markets",
    lessonsLearned: "International viral moments = global demand. Ship to all regions simultaneously on restock.",
  },
  {
    name: "Grimace Shake",
    launchDate: "2023-07-20",
    socialLikes: "980K",
    prPickups: 18,
    salesImpact: "Top 5 Jibbitz for July-Aug 2023",
    highlight: "Cross-promoted by McDonald's socials (free reach)",
    lessonsLearned: "Brand collabs amplify both ways. The licensing investment paid for itself in earned media.",
  },
];
