// Strategy Detail Pages - Content
// Each strategy maps to a recommended action from the dashboard

const STRATEGIES = {
  "carbon-transparency": {
    title: "Strengthen Carbon Transparency",
    type: "Close Gap",
    priority: "high",
    heroStat: "24-point gap vs. category leader",
    summary: "Crocs scores 55 on Carbon Transparency vs. the peer average of 78 and category leader at 95. This is the single biggest credibility gap in Crocs' sustainability positioning. Consumers and regulators are increasingly demanding product-level carbon data, and competitors are racing to own this space.",
    whyNow: [
      "EU Corporate Sustainability Reporting Directive (CSRD) requires Scope 3 disclosure for large companies starting 2026",
      "Allbirds has set the bar with per-product carbon labeling — consumers now expect it",
      "SEC climate disclosure rules are driving investor pressure on carbon transparency",
      "67% of Gen Z consumers say they would switch brands for better carbon transparency (Deloitte 2025)",
    ],
    competitorMoves: [
      { brand: "Allbirds", action: "Carbon footprint label on every product since 2020, now with real-time LCA data dashboard", impact: "Industry gold standard — 95/100 score" },
      { brand: "Nike", action: "Move to Zero sustainability scores on Nike.com product pages", impact: "80% of product lines now scored" },
      { brand: "Adidas", action: "Made to Be Remade QR codes linking to full lifecycle data", impact: "Consumer engagement up 40% on sustainable lines" },
    ],
    actions: [
      {
        title: "Commission product-level Life Cycle Assessment (LCA)",
        timeline: "Q2 2026",
        detail: "Partner with a third-party LCA firm (e.g., Quantis, PRé Sustainability) to calculate carbon footprint for the Classic Clog, Literide, and Bistro lines. Start with top 3 SKUs by volume.",
        effort: "medium",
        impact: "high",
      },
      {
        title: "Publish carbon footprint on Crocs.com product pages",
        timeline: "Q3 2026",
        detail: "Display kg CO2e per pair on product detail pages, similar to Allbirds' model. Include a comparison benchmark ('X% lower than industry average'). Use a simple icon-based design consistent with Crocs' playful brand.",
        effort: "medium",
        impact: "high",
      },
      {
        title: "Issue inaugural Carbon Transparency Report",
        timeline: "Q4 2026",
        detail: "Publish a standalone report covering Scope 1, 2, and 3 emissions with year-over-year reduction targets. Include bio-Croslite impact data and supply chain emissions map. Align with TCFD and GHG Protocol frameworks.",
        effort: "high",
        impact: "high",
      },
      {
        title: "Set science-based carbon reduction targets (SBTi)",
        timeline: "Q1 2027",
        detail: "Submit near-term and long-term targets to the Science Based Targets initiative. This provides third-party validation and positions Crocs alongside Nike and Puma who already have approved SBTi targets.",
        effort: "high",
        impact: "high",
      },
    ],
    kpis: [
      { metric: "Carbon Transparency Score", current: "55", target: "78+", timeline: "12 months" },
      { metric: "Products with carbon labels", current: "0%", target: "50%", timeline: "18 months" },
      { metric: "Scope 3 emissions mapped", current: "Partial", target: "90%+", timeline: "12 months" },
      { metric: "SBTi commitment", current: "None", target: "Targets submitted", timeline: "18 months" },
    ],
    risks: [
      { risk: "LCA reveals unfavorable numbers", mitigation: "Frame as a baseline — transparency itself is the story. 'We measured so we can improve.'" },
      { risk: "Consumer confusion with carbon data", mitigation: "Use relative comparisons ('30% less than avg shoe') not raw numbers. A/B test label designs." },
      { risk: "Greenwashing accusations if targets aren't met", mitigation: "Set conservative, achievable near-term targets. Report annually with honest progress updates." },
    ],
    budget: "$200K–$350K Year 1 (LCA study: $80K, reporting infrastructure: $70K, website integration: $50K, SBTi commitment: $50K–$150K)",
  },

  "circular-programs": {
    title: "Strengthen Circular Programs",
    type: "Close Gap",
    priority: "high",
    heroStat: "22-point gap vs. peer average",
    summary: "Crocs scores 50 on Circular Programs vs. the peer average of 72 and category leader at 90. Circularity is the #1 most common pillar across tracked brands — 4 of 9 peers actively market circular initiatives. Crocs' durable, single-material construction (Croslite) is actually a circularity advantage that's completely under-marketed.",
    whyNow: [
      "Croslite is a single-material polymer — ideal for closed-loop recycling if collection infrastructure exists",
      "Nike Refurbished and Adidas Made to Be Remade have set consumer expectations for take-back programs",
      "Extended Producer Responsibility (EPR) legislation is expanding globally — get ahead of mandates",
      "Birkenstock's lifetime repair guarantee drove their sentiment score to 85% — highest in the peer set",
    ],
    competitorMoves: [
      { brand: "Nike", action: "Nike Refurbished program in 300+ stores — reselling lightly worn returns", impact: "Revenue-positive sustainability program" },
      { brand: "Adidas", action: "Made to Be Remade 3.0 with QR-code return system and material credit rewards", impact: "3rd generation — strong consumer adoption" },
      { brand: "Birkenstock", action: "50 in-store repair stations + mail-in resoling with lifetime guarantee", impact: "Highest consumer sentiment score (85%)" },
      { brand: "Puma", action: "RE:SUEDE biodegradable sneaker with industrial composting", impact: "90% biodegradation proven in 18-month trial" },
    ],
    actions: [
      {
        title: "Launch 'Crocs Come Back' take-back program",
        timeline: "Q2 2026",
        detail: "Start with a pilot in 50 retail locations and online prepaid-label returns. Collected Crocs are sorted: wearable pairs get cleaned and resold as 'Crocs Renewed' at discount; worn-out pairs are ground into Croslite feedstock for new products. Offer $5 Crocs credit per returned pair.",
        effort: "high",
        impact: "high",
      },
      {
        title: "Develop Croslite-to-Croslite recycling process",
        timeline: "Q3 2026",
        detail: "Partner with materials recycling firm to validate closed-loop Croslite recycling at scale. Croslite's single-material composition should yield high recycling efficiency vs. multi-material shoes. Target: 30% recycled Croslite content in new products by 2028.",
        effort: "high",
        impact: "high",
      },
      {
        title: "Launch 'Crocs Renewed' resale channel",
        timeline: "Q3 2026",
        detail: "Sell cleaned, refurbished Crocs at 40-50% discount through dedicated section on Crocs.com and select retail. Similar to Nike Refurbished and Patagonia Worn Wear. Drives revenue while reinforcing durability messaging.",
        effort: "medium",
        impact: "high",
      },
      {
        title: "Publish circular design principles",
        timeline: "Q4 2026",
        detail: "Document and publicize Crocs' design-for-circularity approach: single-material construction, no adhesives, easy disassembly. Create a 'Circular by Design' badge for qualifying products.",
        effort: "low",
        impact: "medium",
      },
    ],
    kpis: [
      { metric: "Circular Programs Score", current: "50", target: "72+", timeline: "12 months" },
      { metric: "Pairs collected via take-back", current: "0", target: "100K", timeline: "12 months" },
      { metric: "Recycled Croslite content", current: "0%", target: "15%", timeline: "18 months" },
      { metric: "Crocs Renewed revenue", current: "$0", target: "$2M+", timeline: "12 months" },
    ],
    risks: [
      { risk: "Low take-back participation rates", mitigation: "Incentivize with Crocs credit. Partner with retail and e-commerce for frictionless returns." },
      { risk: "Croslite recycling quality issues", mitigation: "Start with non-cosmetic applications (insoles, playground surfaces) before closed-loop reuse." },
      { risk: "Cannibalization of new sales", mitigation: "Nike Refurbished data shows resale brings new customers into the brand, not cannibalization." },
    ],
    budget: "$400K–$600K Year 1 (take-back logistics: $200K, recycling R&D: $150K, Renewed platform: $100K, marketing: $100K)",
  },

  "consumer-education": {
    title: "Strengthen Consumer Education",
    type: "Close Gap",
    priority: "high",
    heroStat: "23-point gap vs. peer average",
    summary: "Crocs scores 45 on Consumer Education vs. the peer average of 68 and category leader at 90. Crocs is making real sustainability progress (bio-Croslite, carbon reduction) but consumers don't know about it. The story isn't being told in a way that reaches and resonates with the audience.",
    whyNow: [
      "Crocs' bio-Croslite initiative (35% bio-content achieved) is a genuinely strong story that's under-told",
      "Allbirds' carbon labeling success proves consumers engage with sustainability data when presented simply",
      "72% of millennials are willing to pay more for sustainable products but need proof (NielsenIQ 2025)",
      "Crocs' playful brand voice is a unique asset — sustainability messaging doesn't have to be serious",
    ],
    competitorMoves: [
      { brand: "Allbirds", action: "Carbon footprint printed on every shoe box, every product page, every ad", impact: "Brand is synonymous with sustainability" },
      { brand: "Nike", action: "Sustainability scores on product pages + 'Move to Zero' content hub", impact: "Education integrated into shopping experience" },
      { brand: "Adidas", action: "QR codes on Made to Be Remade products linking to lifecycle journey", impact: "Interactive, product-specific education" },
    ],
    actions: [
      {
        title: "Create 'What's Inside Your Crocs' content series",
        timeline: "Q2 2026",
        detail: "Short-form video series (TikTok, Reels, YouTube Shorts) showing Croslite material science in Crocs' signature playful tone. Episodes: 'What is Croslite?', 'From Sugarcane to Shoe', 'Why Your Crocs Last Forever'. Target: 10M views across series.",
        effort: "medium",
        impact: "high",
      },
      {
        title: "Add sustainability storytelling to product pages",
        timeline: "Q2 2026",
        detail: "Every product page gets a collapsible 'Sustainability' section showing: bio-content %, carbon footprint vs. average shoe, material origin, end-of-life options. Use icons and progress bars, not walls of text.",
        effort: "medium",
        impact: "high",
      },
      {
        title: "Launch Crocs Sustainability Hub",
        timeline: "Q3 2026",
        detail: "Dedicated landing page on Crocs.com aggregating all sustainability initiatives, progress data, goals, and timelines. Include an interactive 'Crocs Impact Calculator' showing collective impact of customer base. Update quarterly.",
        effort: "medium",
        impact: "medium",
      },
      {
        title: "Integrate sustainability into Jibbitz storytelling",
        timeline: "Q3 2026",
        detail: "Launch a 'Green Jibbitz' line made from recycled materials with educational packaging. Each Jibbitz comes with a micro-story about the material source. Bridges Crocs' most beloved product with sustainability narrative.",
        effort: "low",
        impact: "medium",
      },
    ],
    kpis: [
      { metric: "Consumer Education Score", current: "45", target: "68+", timeline: "12 months" },
      { metric: "Sustainability content views", current: "Low", target: "25M+ annually", timeline: "12 months" },
      { metric: "Product page sustainability engagement", current: "N/A", target: "15%+ click-through", timeline: "6 months" },
      { metric: "Aided sustainability awareness", current: "TBD (baseline)", target: "+20 pts", timeline: "12 months" },
    ],
    risks: [
      { risk: "Content feels preachy or off-brand", mitigation: "Keep Crocs' playful, irreverent voice. 'We're making shoes out of sugarcane. It's weird. It works.'" },
      { risk: "Low engagement on sustainability content", mitigation: "Lead with entertainment, not education. The sustainability message is the payload, not the hook." },
    ],
    budget: "$150K–$250K Year 1 (content production: $100K, web integration: $50K, paid distribution: $50K–$100K)",
  },

  "third-party-certs": {
    title: "Strengthen Third-Party Certifications",
    type: "Close Gap",
    priority: "high",
    heroStat: "24-point gap — largest gap in the scorecard",
    summary: "Crocs scores 50 on Third-Party Certifications vs. the peer average of 74 and category leader at 92. This is Crocs' single largest gap. Third-party certifications provide independent validation that turns sustainability claims into verified facts — critical for combating greenwashing skepticism.",
    whyNow: [
      "Greenwashing lawsuits have surged 300% since 2023 — third-party validation is legal protection",
      "Retailers (Nordstrom, REI, Zalando) increasingly require sustainability certifications for shelf placement",
      "B Corp, bluesign, and SBTi are becoming table stakes — competitors already have them",
      "EU Green Claims Directive (2026) will require substantiation for any environmental marketing claim",
    ],
    competitorMoves: [
      { brand: "Allbirds", action: "B Corp certified, certified carbon neutral, FSC-certified packaging", impact: "Triple-certified — the most validated brand in the peer set" },
      { brand: "Nike", action: "SBTi approved targets, bluesign materials, Fair Labor Association accredited", impact: "Comprehensive certification portfolio" },
      { brand: "Puma", action: "SBTi targets, Fair Wages program, EP&L (Environmental Profit & Loss)", impact: "Quantified environmental accounting" },
    ],
    actions: [
      {
        title: "Achieve bluesign system partner status",
        timeline: "Q2–Q3 2026",
        detail: "bluesign certifies responsible chemical management and resource efficiency. Apply for system partner status and begin certifying Croslite production. This is the most attainable certification with highest signal value for footwear.",
        effort: "medium",
        impact: "high",
      },
      {
        title: "Submit SBTi near-term targets",
        timeline: "Q3 2026",
        detail: "Commit to the Science Based Targets initiative and submit 1.5°C-aligned reduction targets. Requires Scope 1, 2, and partial Scope 3 mapping (pairs well with Carbon Transparency workstream). Nike, Adidas, and Puma already have approved targets.",
        effort: "high",
        impact: "high",
      },
      {
        title: "Pursue USDA BioPreferred certification for bio-Croslite",
        timeline: "Q3 2026",
        detail: "Bio-based Croslite (35% bio-content and growing) qualifies for USDA BioPreferred label. This is a unique certification opportunity that no competitor can match — it validates Crocs' signature material innovation.",
        effort: "low",
        impact: "high",
      },
      {
        title: "Evaluate B Corp certification feasibility",
        timeline: "Q4 2026",
        detail: "Complete the B Impact Assessment to identify gaps. B Corp is a 12–18 month process but carries enormous brand value. Allbirds' B Corp status is central to their positioning. Commission internal assessment first to determine readiness.",
        effort: "high",
        impact: "high",
      },
    ],
    kpis: [
      { metric: "Third-Party Certs Score", current: "50", target: "74+", timeline: "12 months" },
      { metric: "Active certifications", current: "~1", target: "3+", timeline: "18 months" },
      { metric: "SBTi status", current: "None", target: "Committed", timeline: "9 months" },
      { metric: "Retailer sustainability qualification", current: "Partial", target: "Full compliance", timeline: "12 months" },
    ],
    risks: [
      { risk: "Certification audits reveal supply chain issues", mitigation: "Conduct pre-assessment gap analysis before formal application. Fix issues before they become public." },
      { risk: "Certification costs and ongoing compliance burden", mitigation: "Start with highest-ROI certs (bluesign, USDA BioPreferred). Phase B Corp as a Year 2 goal." },
    ],
    budget: "$100K–$200K Year 1 (bluesign: $30K, SBTi: $50K, USDA BioPreferred: $10K, B Corp assessment: $20K–$50K, consulting: $40K)",
  },

  "carbon-labeling": {
    title: "Develop a Carbon Labeling Initiative",
    type: "Emerging Trend",
    priority: "high",
    heroStat: "Trend strength: 92/100",
    summary: "Carbon Labeling is the #1 emerging sustainability theme, with a trend strength of 92/100. Allbirds pioneered product-level carbon labeling and it's rapidly becoming an industry expectation. Crocs' single-material construction makes LCA straightforward — this is a natural fit.",
    whyNow: [
      "Carbon labeling is the fastest-growing consumer expectation in sustainable fashion",
      "Allbirds proved the model works — consumers engage and it drives purchase intent",
      "EU and California are both advancing mandatory carbon labeling legislation",
      "Croslite's simple material composition makes LCA cheaper and more accurate than multi-material competitors",
    ],
    competitorMoves: [
      { brand: "Allbirds", action: "Carbon footprint number printed on every product — from shoe box to product page", impact: "Defined the category. 95/100 Carbon Transparency score" },
      { brand: "Nike", action: "Sustainability scores rolling out across Nike.com", impact: "Mass-market adoption signal" },
    ],
    actions: [
      {
        title: "Complete LCA for top 10 SKUs",
        timeline: "Q2 2026",
        detail: "Commission cradle-to-grave lifecycle assessments for the 10 highest-volume products. Focus on Classic Clog, Classic Slide, Literide, and Bistro. Use ISO 14044-compliant methodology for defensibility.",
        effort: "medium",
        impact: "high",
      },
      {
        title: "Design Crocs carbon label system",
        timeline: "Q3 2026",
        detail: "Create a simple, on-brand carbon label. Instead of raw kg CO2e (confusing), use a comparative scale: 'This Clog = X kg CO2e — Y% less than the average shoe.' Match Crocs' visual identity — playful, colorful, accessible. Test with consumer panels.",
        effort: "medium",
        impact: "high",
      },
      {
        title: "Roll out labels on packaging and product pages",
        timeline: "Q4 2026",
        detail: "Phase 1: digital labels on Crocs.com product pages. Phase 2: physical labels on shoe boxes. Phase 3: hang tags. Include QR code linking to full LCA methodology for transparency.",
        effort: "medium",
        impact: "high",
      },
      {
        title: "PR launch: 'We Measured. Here's the Number.'",
        timeline: "Q4 2026",
        detail: "Major press campaign announcing carbon labeling. Frame Crocs as a mass-market brand making carbon data accessible to everyone — not just premium eco-brands. Pitch: 'If a $50 Clog can tell you its carbon footprint, every shoe should.'",
        effort: "medium",
        impact: "high",
      },
    ],
    kpis: [
      { metric: "Products with carbon labels", current: "0", target: "Top 10 SKUs", timeline: "9 months" },
      { metric: "Consumer awareness of Crocs carbon data", current: "0%", target: "30%+", timeline: "12 months" },
      { metric: "PR impressions from launch", current: "N/A", target: "50M+", timeline: "At launch" },
    ],
    risks: [
      { risk: "Carbon numbers are higher than Allbirds", mitigation: "Don't compare to Allbirds — compare to industry average (Crocs likely wins). Frame the story around transparency, not perfection." },
      { risk: "Methodology challenged by critics", mitigation: "Use ISO 14044 compliance and third-party verification. Publish full methodology. Transparency is the shield." },
    ],
    budget: "$150K–$250K (LCA studies: $80K, label design & testing: $30K, web/packaging integration: $40K, PR campaign: $50K–$100K)",
  },

  "regenerative-agriculture": {
    title: "Develop a Regenerative Agriculture Initiative",
    type: "Emerging Trend",
    priority: "high",
    heroStat: "Trend strength: 85/100",
    summary: "Regenerative Agriculture is the #2 emerging sustainability theme at 85/100 trend strength. With bio-based Croslite already sourcing sugarcane-derived materials, Crocs has a natural entry point to tell a regenerative agriculture story that most footwear brands can't credibly claim.",
    whyNow: [
      "Consumer interest in regenerative agriculture has grown 400% since 2022 (Google Trends)",
      "Allbirds' regenerative wool program has become a central brand pillar",
      "Bio-Croslite's sugarcane sourcing can be upgraded to regenerative sugarcane sourcing",
      "Patagonia's Regenerative Organic Certified program proved the model works at scale in apparel",
    ],
    competitorMoves: [
      { brand: "Allbirds", action: "Regenerative wool sourcing from New Zealand farms, with verified soil carbon data", impact: "Differentiated material story competitors can't copy" },
    ],
    actions: [
      {
        title: "Map and audit current sugarcane supply chain",
        timeline: "Q2 2026",
        detail: "Identify current bio-Croslite sugarcane suppliers and their agricultural practices. Determine baseline soil health, pesticide use, water consumption, and labor practices. This assessment informs the regenerative transition roadmap.",
        effort: "medium",
        impact: "medium",
      },
      {
        title: "Partner with regenerative sugarcane producers",
        timeline: "Q3 2026",
        detail: "Identify and contract with sugarcane producers practicing regenerative agriculture (cover cropping, reduced tillage, composting, integrated pest management). Brazil's sugarcane sector has emerging regen programs. Start with 10-20% of supply.",
        effort: "high",
        impact: "high",
      },
      {
        title: "Launch 'Grown, Not Drilled' campaign",
        timeline: "Q4 2026",
        detail: "Marketing campaign connecting the sugarcane field to the finished Clog. Show the farms, the farmers, the soil. Message: 'Your Crocs started as sugarcane, grown in soil that's getting healthier every year.' Video content for social, long-form for brand site.",
        effort: "medium",
        impact: "high",
      },
      {
        title: "Pursue Regenerative Organic Certification (ROC)",
        timeline: "2027",
        detail: "Work with supply chain partners toward ROC certification for sugarcane inputs. This provides the gold-standard third-party validation for regenerative claims. Long-term goal but the pursuit itself is a powerful story.",
        effort: "high",
        impact: "high",
      },
    ],
    kpis: [
      { metric: "Sugarcane from regen sources", current: "0%", target: "15%", timeline: "18 months" },
      { metric: "'Grown Not Drilled' campaign reach", current: "N/A", target: "30M impressions", timeline: "At launch" },
      { metric: "Supply chain mapped", current: "Partial", target: "100%", timeline: "6 months" },
    ],
    risks: [
      { risk: "Regenerative sugarcane supply is limited", mitigation: "Start small (10-20%) and grow. The commitment and trajectory matter more than immediate 100% conversion." },
      { risk: "Higher input costs for regenerative sourcing", mitigation: "Regenerative sourcing premium is typically 5-15%. Offset with marketing value and potential carbon credit revenue from improved soil." },
    ],
    budget: "$100K–$200K Year 1 (supply chain audit: $40K, supplier partnerships: $30K, campaign: $50K–$100K, certification prep: $30K)",
  },

  "campaign-volume": {
    title: "Scale Campaign Volume",
    type: "Increase Visibility",
    priority: "medium",
    heroStat: "34 campaigns vs. 43 peer average",
    summary: "Crocs runs 34 sustainability campaigns vs. a peer average of 43. Nike leads with 82. Higher campaign volume correlates with stronger consumer sentiment across all tracked brands — the brands talking more about sustainability are being perceived as more sustainable.",
    whyNow: [
      "Sustainability messaging volume is rising industry-wide (+12% QoQ) — staying flat means falling behind",
      "Crocs has strong stories to tell (bio-Croslite, carbon reduction) but they're not getting enough airtime",
      "Social algorithms reward consistency — sporadic sustainability posts get buried",
      "Nike's 82-campaign volume correlates with their 81% sentiment score; Crocs' 34 campaigns correlate with 74%",
    ],
    competitorMoves: [
      { brand: "Nike", action: "82 campaigns per period — integrated sustainability messaging across all channels", impact: "Volume leader with highest overall score (91)" },
      { brand: "Adidas", action: "76 campaigns — Made to Be Remade as a persistent content franchise", impact: "Consistent presence drives 79% sentiment" },
      { brand: "Allbirds", action: "68 campaigns — sustainability IS the brand, every post is a sustainability post", impact: "Highest sentiment score (88%)" },
    ],
    actions: [
      {
        title: "Create a sustainability content calendar",
        timeline: "Q2 2026",
        detail: "Map out 12 months of sustainability content across channels: Instagram, TikTok, X, LinkedIn, YouTube. Plan 2-3 posts per week (up from current ~1). Include recurring series ('Material Monday', 'Croslite Chronicles'), reactive moments (Earth Day, World Oceans Day), and product launches.",
        effort: "low",
        impact: "high",
      },
      {
        title: "Embed sustainability messaging in existing campaigns",
        timeline: "Immediate",
        detail: "Don't create separate sustainability campaigns — add sustainability angles to every product launch, collab drop, and seasonal campaign. Every Jibbitz drop can mention recycled materials. Every new colorway can reference bio-Croslite progress. This multiplies volume without multiplying budget.",
        effort: "low",
        impact: "high",
      },
      {
        title: "Launch employee advocacy program",
        timeline: "Q2 2026",
        detail: "Equip Crocs employees with shareable sustainability content for their personal LinkedIn and social channels. 500 employees sharing = 500 micro-campaigns at zero media cost. Provide templates, talking points, and approval guidelines.",
        effort: "low",
        impact: "medium",
      },
      {
        title: "Partner with sustainability micro-influencers",
        timeline: "Q2 2026",
        detail: "Identify 20-30 sustainability-focused creators (50K-500K followers) for always-on partnership. They create authentic content featuring Crocs' sustainability story. More credible than brand-created content, expands reach beyond Crocs' owned channels.",
        effort: "medium",
        impact: "high",
      },
    ],
    kpis: [
      { metric: "Campaign volume", current: "34", target: "50+", timeline: "6 months" },
      { metric: "Sustainability share of voice", current: "~8%", target: "15%+", timeline: "12 months" },
      { metric: "Social engagement rate on sust. content", current: "TBD", target: "2x baseline", timeline: "6 months" },
    ],
    risks: [
      { risk: "Quantity over quality — spamming sustainability content", mitigation: "Set quality bar: every post must either teach something, show progress, or inspire action. No empty platitudes." },
      { risk: "Audience fatigue", mitigation: "Vary formats (video, carousel, infographic, UGC) and tone (serious, funny, surprising). Crocs' brand voice is an asset here." },
    ],
    budget: "$75K–$150K Year 1 (content creation: $50K, influencer partnerships: $50K–$100K, employee program: $10K)",
  },

  "adopt-pillar": {
    title: "Adopt Missing Sustainability Pillars",
    type: "Adopt Pillar",
    priority: "medium",
    heroStat: "Multiple pillars used by peers but not by Crocs",
    summary: "Several sustainability pillars are actively marketed by multiple competitors but absent from Crocs' messaging. Adopting even one or two of these pillars would broaden Crocs' sustainability positioning and close perception gaps with consumers comparing brands.",
    whyNow: [
      "Consumers compare brands across multiple sustainability dimensions — gaps are visible",
      "Several of these pillars (Recycled Materials, Renewable Energy) align with initiatives Crocs may already be pursuing internally",
      "Adding pillars is primarily a messaging/marketing exercise if underlying programs already exist",
    ],
    competitorMoves: [
      { brand: "Multiple peers", action: "Recycled Materials is used by Skechers, Hoka, and others — Crocs could likely claim this", impact: "Low-hanging fruit messaging opportunity" },
      { brand: "Nike + New Balance", action: "Renewable Energy messaging in operations and supply chain", impact: "Signals operational commitment beyond products" },
    ],
    actions: [
      {
        title: "Audit current practices against missing pillars",
        timeline: "Q2 2026",
        detail: "Review Crocs' operations and supply chain for existing efforts that map to popular pillars: recycled content in packaging or products, renewable energy in facilities, water management practices, fair labor programs. Many companies under-market what they already do.",
        effort: "low",
        impact: "high",
      },
      {
        title: "Add 'Recycled Materials' to pillar messaging",
        timeline: "Q2 2026",
        detail: "If Crocs uses any recycled content in packaging, hang tags, poly bags, or product components — start messaging it. Even recycled packaging counts. Create a clear claim: 'X% of our packaging is recycled or recyclable.'",
        effort: "low",
        impact: "medium",
      },
      {
        title: "Add 'Renewable Energy' to pillar messaging",
        timeline: "Q3 2026",
        detail: "If any Crocs facilities or key suppliers use renewable energy, begin messaging this. If not, purchasing Renewable Energy Certificates (RECs) for corporate operations is a cost-effective entry point (~$5-15K/year).",
        effort: "low",
        impact: "medium",
      },
      {
        title: "Evaluate 'Water Stewardship' as a brand pillar",
        timeline: "Q3 2026",
        detail: "Croslite production is low-water compared to traditional shoe manufacturing (no leather tanning, no textile dyeing). If this is validated by LCA data, it's a powerful differentiator. 'Your Crocs used 90% less water than the average shoe.'",
        effort: "medium",
        impact: "high",
      },
    ],
    kpis: [
      { metric: "Active sustainability pillars", current: "3", target: "5-6", timeline: "9 months" },
      { metric: "Messaging coverage across dimensions", current: "Narrow", target: "Broad", timeline: "12 months" },
    ],
    risks: [
      { risk: "Claiming pillars without substance behind them", mitigation: "Only add pillars backed by real data or programs. The EU Green Claims Directive will penalize unsubstantiated claims." },
    ],
    budget: "$25K–$50K (audit: $15K, messaging development: $10K, RECs if needed: $5-15K)",
  },

  "peer-campaigns": {
    title: "Study & Respond to High-Engagement Peer Campaigns",
    type: "Competitive Response",
    priority: "medium",
    heroStat: "2 peer campaigns achieved 'Very High' engagement",
    summary: "Nike's 'Move to Zero: Season 5' and Allbirds' 'Flight Status: Carbon Dashboard' both achieved 'Very High' consumer engagement. Analyzing their formats, messaging frameworks, and channel strategies can directly inform Crocs' next campaign cycle.",
    whyNow: [
      "These campaigns represent the current state-of-the-art in sustainability marketing",
      "Their success provides a proven template — adapt, don't copy, for Crocs' brand voice",
      "Both campaigns solved the engagement problem — consumers actively sought out sustainability content",
    ],
    competitorMoves: [
      { brand: "Nike", action: "Move to Zero Season 5: circular design principles across 80% of product lines with consumer-facing sustainability scores", impact: "Very High engagement — multi-channel" },
      { brand: "Allbirds", action: "Flight Status Carbon Dashboard: real-time public carbon dashboard with per-product lifecycle emissions and industry benchmarking", impact: "Very High engagement — digital" },
    ],
    actions: [
      {
        title: "Deep-dive analysis of Move to Zero and Flight Status",
        timeline: "Immediate",
        detail: "Document everything: channel mix, content formats, posting cadence, creative assets, landing page structure, calls-to-action, influencer involvement, PR strategy. Create a competitive teardown deck for the marketing team.",
        effort: "low",
        impact: "high",
      },
      {
        title: "Identify what's adaptable for Crocs' brand",
        timeline: "Q2 2026",
        detail: "Nike's approach: make sustainability scores part of the product shopping experience. Allbirds' approach: radical transparency with real-time data. Both can be adapted. Crocs' version: 'Clog Score' — a fun, on-brand sustainability rating system for every product.",
        effort: "low",
        impact: "high",
      },
      {
        title: "Prototype a Crocs sustainability engagement campaign",
        timeline: "Q2 2026",
        detail: "Design a campaign that matches or exceeds the engagement of Move to Zero and Flight Status. Concept: 'The Crocs Carbon Challenge' — gamified sustainability where customers earn points (and Jibbitz rewards) for participating in take-back programs, choosing bio-Croslite products, and sharing sustainability content.",
        effort: "medium",
        impact: "high",
      },
      {
        title: "Set up ongoing competitive monitoring",
        timeline: "Immediate",
        detail: "Subscribe to competitor newsletter and social feeds. Set up Google Alerts and social listening for competitor sustainability campaigns. Brief the team monthly on what's working for others and how Crocs should respond.",
        effort: "low",
        impact: "medium",
      },
    ],
    kpis: [
      { metric: "Competitive teardown completed", current: "No", target: "Yes", timeline: "2 weeks" },
      { metric: "Campaign engagement level", current: "Medium", target: "Very High", timeline: "6 months" },
      { metric: "Competitor monitoring cadence", current: "Ad hoc", target: "Monthly briefings", timeline: "Immediate" },
    ],
    risks: [
      { risk: "Copying competitors too closely", mitigation: "Adapt the strategy, not the execution. Crocs' brand voice and audience are different — what works for Nike's aspirational tone needs to be translated into Crocs' playful, accessible voice." },
    ],
    budget: "$15K–$30K (analysis: $10K, campaign prototype: $20K, monitoring tools: $5K/year)",
  },

  "sentiment-gap": {
    title: "Close Sentiment Gap with Category Leader",
    type: "Brand Perception",
    priority: "low",
    heroStat: "74% vs. leader at 88%",
    summary: "Crocs' consumer sustainability sentiment is 74% positive vs. Allbirds at 88% (the leader) and Birkenstock at 85%. While Crocs' sentiment is positive, closing this 14-point gap would meaningfully strengthen brand perception and support premium positioning.",
    whyNow: [
      "Sustainability sentiment is increasingly correlated with willingness-to-pay and brand loyalty",
      "Crocs' sentiment (74%) is above neutral but trails the leaders significantly",
      "The gap isn't about doing more — it's about communicating better (see: Consumer Education strategy)",
    ],
    competitorMoves: [
      { brand: "Allbirds", action: "Sustainability IS the brand identity — not a side initiative", impact: "88% positive sentiment — highest in peer set" },
      { brand: "Birkenstock", action: "Lifetime repair guarantee and natural materials heritage", impact: "85% sentiment driven by authenticity and longevity" },
    ],
    actions: [
      {
        title: "Conduct consumer perception audit",
        timeline: "Q2 2026",
        detail: "Commission a brand perception study specifically measuring sustainability associations. What do consumers currently associate with Crocs + sustainability? What would change their perception? Use findings to refine messaging strategy.",
        effort: "medium",
        impact: "high",
      },
      {
        title: "Develop authentic sustainability brand narrative",
        timeline: "Q2–Q3 2026",
        detail: "Crocs' sustainability story should be uniquely Crocs: 'We make the most comfortable, most loved shoe in the world — and now we're making it from plants.' Not preachy, not aspirational — practical, fun, honest. Build a brand narrative playbook for all teams.",
        effort: "medium",
        impact: "high",
      },
      {
        title: "Amplify bio-Croslite progress as hero story",
        timeline: "Ongoing",
        detail: "Bio-Croslite is Crocs' strongest sustainability asset. Make '50% bio-content by 2027' the signature claim. Update consumers on progress quarterly. Make it a countdown: '35% → 40% → 45% → 50%.' Consumers love visible progress.",
        effort: "low",
        impact: "high",
      },
      {
        title: "Earn sustainability recognition and awards",
        timeline: "Q3 2026",
        detail: "Apply for sustainability awards (Sustainable Apparel Coalition, FN Sustainability Awards, Fast Company Innovation). Third-party recognition shifts perception faster than self-promotion. Birkenstock's high sentiment is partly driven by heritage and awards.",
        effort: "low",
        impact: "medium",
      },
    ],
    kpis: [
      { metric: "Consumer sentiment score", current: "74%", target: "82%+", timeline: "12 months" },
      { metric: "Unaided sustainability association", current: "TBD", target: "+15 pts", timeline: "12 months" },
      { metric: "Sustainability awards won", current: "0", target: "2+", timeline: "12 months" },
    ],
    risks: [
      { risk: "Sentiment moves slowly — hard to see short-term impact", mitigation: "Track leading indicators (social engagement, press mentions, unaided awareness) monthly. Sentiment is a lagging indicator." },
    ],
    budget: "$50K–$100K Year 1 (perception study: $30K, narrative development: $20K, award submissions: $5K, ongoing comms: $20K)",
  },
};
